function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "Blueberry", file = "media/maps/Blueberry/spawnpoints.lua" },
		{ name = "Cedar Hill", file = "media/maps/Cedar Hill/spawnpoints.lua" },
		{ name = "Dirkerdam", file = "media/maps/Dirkerdam/spawnpoints.lua" },
		{ name = "Dirkerdam west", file = "media/maps/Dirkerdam west/spawnpoints.lua" },
		{ name = "Dirkerdam_Spawns", file = "media/maps/Dirkerdam_Spawns/spawnpoints.lua" },
		{ name = "Florius", file = "media/maps/Florius/spawnpoints.lua" },
		{ name = "Pertville", file = "media/maps/Pertville/spawnpoints.lua" },
		{ name = "Tashtego", file = "media/maps/Tashtego/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "Otr", file = "media/maps/Otr/spawnpoints.lua" },
		{ name = "Over the River - Secondary Route", file = "media/maps/Over the River - Secondary Route/spawnpoints.lua" },
		{ name = "Taylorsville_bridge_to_Dirkerdam", file = "media/maps/Taylorsville_bridge_to_Dirkerdam/spawnpoints.lua" },
		{ name = "The Frigate", file = "media/maps/The Frigate/spawnpoints.lua" },
		{ name = "MotoriousExpandedSpawnZones", file = "media/maps/MotoriousExpandedSpawnZones/spawnpoints.lua" },
		{ name = "BarcoAbandonado", file = "media/maps/BarcoAbandonado/spawnpoints.lua" },
		{ name = "Factory", file = "media/maps/Factory/spawnpoints.lua" },
		{ name = "MilitaryComplex", file = "media/maps/MilitaryComplex/spawnpoints.lua" },
		{ name = "Riverside Gunstore", file = "media/maps/Riverside Gunstore/spawnpoints.lua" },
		{ name = "Mansion", file = "media/maps/Mansion/spawnpoints.lua" },
		{ name = "mechanicsplaces", file = "media/maps/mechanicsplaces/spawnpoints.lua" },
		{ name = "tluisville", file = "media/maps/tluisville/spawnpoints.lua" },
		{ name = "tmarch", file = "media/maps/tmarch/spawnpoints.lua" },
		{ name = "tvalley", file = "media/maps/tvalley/spawnpoints.lua" },
	}
end
